// Automatically generated by Digital Mars D Compiler v2091

#pragma once

#include <assert.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#if !defined(_d_real)
# define _d_real long double
#endif


// Parsing module d.lib
extern "C" void sayHello();

extern "C" int32_t add(int32_t a, int32_t b);

